# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='kid_first_name',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='kid_last_name',
        ),
        migrations.AddField(
            model_name='kid',
            name='kid_name',
            field=models.CharField(default='None', max_length=40),
        ),
    ]
