# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20180405_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='kid',
        ),
        migrations.AddField(
            model_name='signin',
            name='kid',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Home.Kid'),
            preserve_default=False,
        ),
    ]
