# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20180405_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='place',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AddField(
            model_name='signin',
            name='reason',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AddField(
            model_name='signin',
            name='subject',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AddField(
            model_name='signin',
            name='teacher',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Home.Teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signin',
            name='time_entered',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='signin',
            name='time_left',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
