# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20180409_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='kid_grade',
            field=models.IntegerField(default=7),
        ),
    ]
