# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20180411_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='time_entered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
