# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_kid_time_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='currently_signed_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='signin',
            name='teacher_name',
            field=models.CharField(default='None', max_length=40),
        ),
    ]
