# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20180411_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='kid_id',
            field=models.IntegerField(default=7),
        ),
    ]
