# Generated by Django 2.0.4 on 2018-04-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_signin_kid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='place',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AddField(
            model_name='kid',
            name='reason',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AddField(
            model_name='kid',
            name='subject',
            field=models.CharField(default='None', max_length=40),
        ),
    ]
