# Generated by Django 2.0.4 on 2018-04-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_auto_20180425_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='techer_name',
            new_name='teacher_name',
        ),
        migrations.AddField(
            model_name='kid',
            name='teacher_name',
            field=models.CharField(default='None', max_length=40),
        ),
    ]
