# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-27 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_auto_20180425_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='kid_student_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
