# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_kid_kid_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxSignOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currently_signed_in', models.BooleanField(default=True)),
                ('teacher_name', models.CharField(default='None', max_length=40)),
                ('box_num', models.IntegerField(default=7)),
            ],
        ),
    ]
